import '../globals.css';
import React, { ReactNode } from 'react';

import LanguageSelector from '@/components/LanguageSelector';
import { locales } from '@/config/next-intl';
import { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { notFound } from 'next/navigation';
import { ThemeProvider } from '@/context/ThemeProvider';
import NextTopLoader from 'nextjs-toploader';
import { unstable_setRequestLocale } from 'next-intl/server';
import { cn } from '@/lib/utils';
import Header from '@/components/layout/Header';

interface RootLayoutProps {
  children: ReactNode;
  params: {
    locale: any;
  };
}

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Lianbit',
  description: 'Generated by create next app',
};

export const revalidate = 60;

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function LocaleLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  if (!locales.includes(locale)) notFound();

  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  unstable_setRequestLocale(locale);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <NextTopLoader color="#2663E9" />
          <Header locale={locale}>
            <LanguageSelector />
          </Header>
          {children}
          {/* <Footer locale={locale} /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
