import '../globals.css';
import React, { ReactNode } from 'react';

import LanguageSelector from '@/components/LanguageSelector';
import { locales } from '@/config/next-intl';
import { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { notFound } from 'next/navigation';
import { ThemeProvider } from '@/context/ThemeProvider';
import NextTopLoader from 'nextjs-toploader';
import { unstable_setRequestLocale } from 'next-intl/server';
import { cn } from '@/lib/utils';
import Header from '@/components/layout/Header';
import { NextIntlClientProvider } from 'next-intl';
import { Provider as BalancerProvider } from 'react-wrap-balancer';

interface RootLayoutProps {
  children: ReactNode;
  params: {
    locale: any;
  };
}

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Farhan Aziz Ath Thariq',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  if (!locales.includes(locale)) notFound();
  if (!locales.some((cur) => cur === locale)) notFound();

  unstable_setRequestLocale(locale);

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <NextTopLoader color="#2663E9" />
          <BalancerProvider>
            <NextIntlClientProvider messages={messages}>
              <Header locale={locale}>
                <LanguageSelector />
              </Header>
              {children}
            </NextIntlClientProvider>
          </BalancerProvider>
          {/* <Footer locale={locale} /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
